In [4]:
from kloppy import footovision

dataset = footovision.load_tracking(
    raw_data="kloppy/tests/files/footovision_small_tracking.json",
    meta_data="kloppy/tests/files/footovision_game.json",
)

In [5]:
print(dataset)

<TrackingDataset record_count=5002>

In [6]:
dataset.frames

[<Frame frame_id='0' time='P1T00:00'>,
 <Frame frame_id='1' time='P1T00:00'>,
 <Frame frame_id='2' time='P1T00:00'>,
 <Frame frame_id='3' time='P1T00:00'>,
 <Frame frame_id='4' time='P1T00:00'>,
 <Frame frame_id='5' time='P1T00:00'>,
 <Frame frame_id='6' time='P1T00:00'>,
 <Frame frame_id='7' time='P1T00:00'>,
 <Frame frame_id='8' time='P1T00:00'>,
 <Frame frame_id='9' time='P1T00:00'>,
 <Frame frame_id='10' time='P1T00:00'>,
 <Frame frame_id='11' time='P1T00:00'>,
 <Frame frame_id='12' time='P1T00:00'>,
 <Frame frame_id='13' time='P1T00:01'>,
 <Frame frame_id='14' time='P1T00:01'>,
 <Frame frame_id='15' time='P1T00:01'>,
 <Frame frame_id='16' time='P1T00:01'>,
 <Frame frame_id='17' time='P1T00:01'>,
 <Frame frame_id='18' time='P1T00:01'>,
 <Frame frame_id='19' time='P1T00:01'>,
 <Frame frame_id='20' time='P1T00:01'>,
 <Frame frame_id='21' time='P1T00:01'>,
 <Frame frame_id='22' time='P1T00:01'>,
 <Frame frame_id='23' time='P1T00:01'>,
 <Frame frame_id='24' time='P1T00:01'>,
 <Frame frame_id='25' time='P1T00:01'>,
 <Frame frame_id='26' time='P1T00:01'>,
 <Frame frame_id='27' time='P1T00:01'>,
 <Frame frame_id='28' time='P1T00:01'>,
 <Frame frame_id='29' time='P1T00:01'>,
 <Frame frame_id='30' time='P1T00:01'>,
 <Frame frame_id='31' time='P1T00:01'>,
 <Frame frame_id='32' time='P1T00:01'>,
 <Frame frame_id='33' time='P1T00:01'>,
 <Frame frame_id='34' time='P1T00:01'>,
 <Frame frame_id='35' time='P1T00:01'>,
 <Frame frame_id='36' time='P1T00:01'>,
 <Frame frame_id='37' time='P1T00:01'>,
 <Frame frame_id='38' time='P1T00:02'>,
 <Frame frame_id='39' time='P1T00:02'>,
 <Frame frame_id='40' time='P1T00:02'>,
 <Frame frame_id='41' time='P1T00:02'>,
 <Frame frame_id='42' time='P1T00:02'>,
 <Frame frame_id='43' time='P1T00:02'>,
 <Frame frame_id='44' time='P1T00:02'>,
 <Frame frame_id='45' time='P1T00:02'>,
 <Frame frame_id='46' time='P1T00:02'>,
 <Frame frame_id='47' time='P1T00:02'>,
 <Frame frame_id='48' time='P1T00:02'>,
 <Frame frame_id='49' time='P1T00:02'>,
 <Frame frame_id='50' time='P1T00:02'>,
 <Frame frame_id='51' time='P1T00:02'>,
 <Frame frame_id='52' time='P1T00:02'>,
 <Frame frame_id='53' time='P1T00:02'>,
 <Frame frame_id='54' time='P1T00:02'>,
 <Frame frame_id='55' time='P1T00:02'>,
 <Frame frame_id='56' time='P1T00:02'>,
 <Frame frame_id='57' time='P1T00:02'>,
 <Frame frame_id='58' time='P1T00:02'>,
 <Frame frame_id='59' time='P1T00:02'>,
 <Frame frame_id='60' time='P1T00:02'>,
 <Frame frame_id='61' time='P1T00:02'>,
 <Frame frame_id='62' time='P1T00:02'>,
 <Frame frame_id='63' time='P1T00:03'>,
 <Frame frame_id='64' time='P1T00:03'>,
 <Frame frame_id='65' time='P1T00:03'>,
 <Frame frame_id='66' time='P1T00:03'>,
 <Frame frame_id='67' time='P1T00:03'>,
 <Frame frame_id='68' time='P1T00:03'>,
 <Frame frame_id='69' time='P1T00:03'>,
 <Frame frame_id='70' time='P1T00:03'>,
 <Frame frame_id='71' time='P1T00:03'>,
 <Frame frame_id='72' time='P1T00:03'>,
 <Frame frame_id='73' time='P1T00:03'>,
 <Frame frame_id='74' time='P1T00:03'>,
 <Frame frame_id='75' time='P1T00:03'>,
 <Frame frame_id='76' time='P1T00:03'>,
 <Frame frame_id='77' time='P1T00:03'>,
 <Frame frame_id='78' time='P1T00:03'>,
 <Frame frame_id='79' time='P1T00:03'>,
 <Frame frame_id='80' time='P1T00:03'>,
 <Frame frame_id='81' time='P1T00:03'>,
 <Frame frame_id='82' time='P1T00:03'>,
 <Frame frame_id='83' time='P1T00:03'>,
 <Frame frame_id='84' time='P1T00:03'>,
 <Frame frame_id='85' time='P1T00:03'>,
 <Frame frame_id='86' time='P1T00:03'>,
 <Frame frame_id='87' time='P1T00:03'>,
 <Frame frame_id='88' time='P1T00:04'>,
 <Frame frame_id='89' time='P1T00:04'>,
 <Frame frame_id='90' time='P1T00:04'>,
 <Frame frame_id='91' time='P1T00:04'>,
 <Frame frame_id='92' time='P1T00:04'>,
 <Frame frame_id='93' time='P1T00:04'>,
 <Frame frame_id='94' time='P1T00:04'>,
 <Frame frame_id='95' time='P1T00:04'>,
 <Frame frame_id='96' time='P1T00:04'>,
 <Frame frame_id='97' time='P1T00:04'>,
 <Frame frame_id='98' time='P1T00:04'>,
 <Frame frame_id='99' time='P1T00:04'>,
 <Frame frame_id='100' time='P1T00:04'>,
 <Frame frame_id='101' time='P1T00:04'>,
 <Frame frame_id='102' time='P1T00:04'>,
 <Frame frame_id='103' time='P1T00:04'>,
 <Frame frame_id='104' time='P1T00:04'>,
 <Frame frame_id='105' time='P1T00:04'>,
 <Frame frame_id='106' time='P1T00:04'>,
 <Frame frame_id='107' time='P1T00:04'>,
 <Frame frame_id='108' time='P1T00:04'>,
 <Frame frame_id='109' time='P1T00:04'>,
 <Frame frame_id='110' time='P1T00:04'>,
 <Frame frame_id='111' time='P1T00:04'>,
 <Frame frame_id='112' time='P1T00:04'>,
 <Frame frame_id='113' time='P1T00:05'>,
 <Frame frame_id='114' time='P1T00:05'>,
 <Frame frame_id='115' time='P1T00:05'>,
 <Frame frame_id='116' time='P1T00:05'>,
 <Frame frame_id='117' time='P1T00:05'>,
 <Frame frame_id='118' time='P1T00:05'>,
 <Frame frame_id='119' time='P1T00:05'>,
 <Frame frame_id='120' time='P1T00:05'>,
 <Frame frame_id='121' time='P1T00:05'>,
 <Frame frame_id='122' time='P1T00:05'>,
 <Frame frame_id='123' time='P1T00:05'>,
 <Frame frame_id='124' time='P1T00:05'>,
 <Frame frame_id='125' time='P1T00:05'>,
 <Frame frame_id='126' time='P1T00:05'>,
 <Frame frame_id='127' time='P1T00:05'>,
 <Frame frame_id='128' time='P1T00:05'>,
 <Frame frame_id='129' time='P1T00:05'>,
 <Frame frame_id='130' time='P1T00:05'>,
 <Frame frame_id='131' time='P1T00:05'>,
 <Frame frame_id='132' time='P1T00:05'>,
 <Frame frame_id='133' time='P1T00:05'>,
 <Frame frame_id='134' time='P1T00:05'>,
 <Frame frame_id='135' time='P1T00:05'>,
 <Frame frame_id='136' time='P1T00:05'>,
 <Frame frame_id='137' time='P1T00:05'>,
 <Frame frame_id='138' time='P1T00:06'>,
 <Frame frame_id='139' time='P1T00:06'>,
 <Frame frame_id='140' time='P1T00:06'>,
 <Frame frame_id='141' time='P1T00:06'>,
 <Frame frame_id='142' time='P1T00:06'>,
 <Frame frame_id='143' time='P1T00:06'>,
 <Frame frame_id='144' time='P1T00:06'>,
 <Frame frame_id='145' time='P1T00:06'>,
 <Frame frame_id='146' time='P1T00:06'>,
 <Frame frame_id='147' time='P1T00:06'>,
 <Frame frame_id='148' time='P1T00:06'>,
 <Frame frame_id='149' time='P1T00:06'>,
 <Frame frame_id='150' time='P1T00:06'>,
 <Frame frame_id='151' time='P1T00:06'>,
 <Frame frame_id='152' time='P1T00:06'>,
 <Frame frame_id='153' time='P1T00:06'>,
 <Frame frame_id='154' time='P1T00:06'>,
 <Frame frame_id='155' time='P1T00:06'>,
 <Frame frame_id='156' time='P1T00:06'>,
 <Frame frame_id='157' time='P1T00:06'>,
 <Frame frame_id='158' time='P1T00:06'>,
 <Frame frame_id='159' time='P1T00:06'>,
 <Frame frame_id='160' time='P1T00:06'>,
 <Frame frame_id='161' time='P1T00:06'>,
 <Frame frame_id='162' time='P1T00:06'>,
 <Frame frame_id='163' time='P1T00:07'>,
 <Frame frame_id='164' time='P1T00:07'>,
 <Frame frame_id='165' time='P1T00:07'>,
 <Frame frame_id='166' time='P1T00:07'>,
 <Frame frame_id='167' time='P1T00:07'>,
 <Frame frame_id='168' time='P1T00:07'>,
 <Frame frame_id='169' time='P1T00:07'>,
 <Frame frame_id='170' time='P1T00:07'>,
 <Frame frame_id='171' time='P1T00:07'>,
 <Frame frame_id='172' time='P1T00:07'>,
 <Frame frame_id='173' time='P1T00:07'>,
 <Frame frame_id='174' time='P1T00:07'>,
 <Frame frame_id='175' time='P1T00:07'>,
 <Frame frame_id='176' time='P1T00:07'>,
 <Frame frame_id='177' time='P1T00:07'>,
 <Frame frame_id='178' time='P1T00:07'>,
 <Frame frame_id='179' time='P1T00:07'>,
 <Frame frame_id='180' time='P1T00:07'>,
 <Frame frame_id='181' time='P1T00:07'>,
 <Frame frame_id='182' time='P1T00:07'>,
 <Frame frame_id='183' time='P1T00:07'>,
 <Frame frame_id='184' time='P1T00:07'>,
 <Frame frame_id='185' time='P1T00:07'>,
 <Frame frame_id='186' time='P1T00:07'>,
 <Frame frame_id='187' time='P1T00:07'>,
 <Frame frame_id='188' time='P1T00:08'>,
 <Frame frame_id='189' time='P1T00:08'>,
 <Frame frame_id='190' time='P1T00:08'>,
 <Frame frame_id='191' time='P1T00:08'>,
 <Frame frame_id='192' time='P1T00:08'>,
 <Frame frame_id='193' time='P1T00:08'>,
 <Frame frame_id='194' time='P1T00:08'>,
 <Frame frame_id='195' time='P1T00:08'>,
 <Frame frame_id='196' time='P1T00:08'>,
 <Frame frame_id='197' time='P1T00:08'>,
 <Frame frame_id='198' time='P1T00:08'>,
 <Frame frame_id='199' time='P1T00:08'>,
 <Frame frame_id='200' time='P1T00:08'>,
 <Frame frame_id='201' time='P1T00:08'>,
 <Frame frame_id='202' time='P1T00:08'>,
 <Frame frame_id='203' time='P1T00:08'>,
 <Frame frame_id='204' time='P1T00:08'>,
 <Frame frame_id='205' time='P1T00:08'>,
 <Frame frame_id='206' time='P1T00:08'>,
 <Frame frame_id='207' time='P1T00:08'>,
 <Frame frame_id='208' time='P1T00:08'>,
 <Frame frame_id='209' time='P1T00:08'>,
 <Frame frame_id='210' time='P1T00:08'>,
 <Frame frame_id='211' time='P1T00:08'>,
 <Frame frame_id='212' time='P1T00:08'>,
 <Frame frame_id='213' time='P1T00:09'>,
 <Frame frame_id='214' time='P1T00:09'>,
 <Frame frame_id='215' time='P1T00:09'>,
 <Frame frame_id='216' time='P1T00:09'>,
 <Frame frame_id='217' time='P1T00:09'>,
 <Frame frame_id='218' time='P1T00:09'>,
 <Frame frame_id='219' time='P1T00:09'>,
 <Frame frame_id='220' time='P1T00:09'>,
 <Frame frame_id='221' time='P1T00:09'>,
 <Frame frame_id='222' time='P1T00:09'>,
 <Frame frame_id='223' time='P1T00:09'>,
 <Frame frame_id='224' time='P1T00:09'>,
 <Frame frame_id='225' time='P1T00:09'>,
 <Frame frame_id='226' time='P1T00:09'>,
 <Frame frame_id='227' time='P1T00:09'>,
 <Frame frame_id='228' time='P1T00:09'>,
 <Frame frame_id='229' time='P1T00:09'>,
 <Frame frame_id='230' time='P1T00:09'>,
 <Frame frame_id='231' time='P1T00:09'>,
 <Frame frame_id='232' time='P1T00:09'>,
 <Frame frame_id='233' time='P1T00:09'>,
 <Frame frame_id='234' time='P1T00:09'>,
 <Frame frame_id='235' time='P1T00:09'>,
 <Frame frame_id='236' time='P1T00:09'>,
 <Frame frame_id='237' time='P1T00:09'>,
 <Frame frame_id='238' time='P1T00:10'>,
 <Frame frame_id='239' time='P1T00:10'>,
 <Frame frame_id='240' time='P1T00:10'>,
 <Frame frame_id='241' time='P1T00:10'>,
 <Frame frame_id='242' time='P1T00:10'>,
 <Frame frame_id='243' time='P1T00:10'>,
 <Frame frame_id='244' time='P1T00:10'>,
 <Frame frame_id='245' time='P1T00:10'>,
 <Frame frame_id='246' time='P1T00:10'>,
 <Frame frame_id='247' time='P1T00:10'>,
 <Frame frame_id='248' time='P1T00:10'>,
 <Frame frame_id='249' time='P1T00:10'>,
 <Frame frame_id='250' time='P1T00:10'>,
 <Frame frame_id='251' time='P1T00:10'>,
 <Frame frame_id='252' time='P1T00:10'>,
 <Frame frame_id='253' time='P1T00:10'>,
 <Frame frame_id='254' time='P1T00:10'>,
 <Frame frame_id='255' time='P1T00:10'>,
 <Frame frame_id='256' time='P1T00:10'>,
 <Frame frame_id='257' time='P1T00:10'>,
 <Frame frame_id='258' time='P1T00:10'>,
 <Frame frame_id='259' time='P1T00:10'>,
 <Frame frame_id='260' time='P1T00:10'>,
 <Frame frame_id='261' time='P1T00:10'>,
 <Frame frame_id='262' time='P1T00:10'>,
 <Frame frame_id='263' time='P1T00:11'>,
 <Frame frame_id='264' time='P1T00:11'>,
 <Frame frame_id='265' time='P1T00:11'>,
 <Frame frame_id='266' time='P1T00:11'>,
 <Frame frame_id='267' time='P1T00:11'>,
 <Frame frame_id='268' time='P1T00:11'>,
 <Frame frame_id='269' time='P1T00:11'>,
 <Frame frame_id='270' time='P1T00:11'>,
 <Frame frame_id='271' time='P1T00:11'>,
 <Frame frame_id='272' time='P1T00:11'>,
 <Frame frame_id='273' time='P1T00:11'>,
 <Frame frame_id='274' time='P1T00:11'>,
 <Frame frame_id='275' time='P1T00:11'>,
 <Frame frame_id='276' time='P1T00:11'>,
 <Frame frame_id='277' time='P1T00:11'>,
 <Frame frame_id='278' time='P1T00:11'>,
 <Frame frame_id='279' time='P1T00:11'>,
 <Frame frame_id='280' time='P1T00:11'>,
 <Frame frame_id='281' time='P1T00:11'>,
 <Frame frame_id='282' time='P1T00:11'>,
 <Frame frame_id='283' time='P1T00:11'>,
 <Frame frame_id='284' time='P1T00:11'>,
 <Frame frame_id='285' time='P1T00:11'>,
 <Frame frame_id='286' time='P1T00:11'>,
 <Frame frame_id='287' time='P1T00:11'>,
 <Frame frame_id='288' time='P1T00:12'>,
 <Frame frame_id='289' time='P1T00:12'>,
 <Frame frame_id='290' time='P1T00:12'>,
 <Frame frame_id='291' time='P1T00:12'>,
 <Frame frame_id='292' time='P1T00:12'>,
 <Frame frame_id='293' time='P1T00:12'>,
 <Frame frame_id='294' time='P1T00:12'>,
 <Frame frame_id='295' time='P1T00:12'>,
 <Frame frame_id='296' time='P1T00:12'>,
 <Frame frame_id='297' time='P1T00:12'>,
 <Frame frame_id='298' time='P1T00:12'>,
 <Frame frame_id='299' time='P1T00:12'>,
 <Frame frame_id='300' time='P1T00:12'>,
 <Frame frame_id='301' time='P1T00:12'>,
 <Frame frame_id='302' time='P1T00:12'>,
 <Frame frame_id='303' time='P1T00:12'>,
 <Frame frame_id='304' time='P1T00:12'>,
 <Frame frame_id='305' time='P1T00:12'>,
 <Frame frame_id='306' time='P1T00:12'>,
 <Frame frame_id='307' time='P1T00:12'>,
 <Frame frame_id='308' time='P1T00:12'>,
 <Frame frame_id='309' time='P1T00:12'>,
 <Frame frame_id='310' time='P1T00:12'>,
 <Frame frame_id='311' time='P1T00:12'>,
 <Frame frame_id='312' time='P1T00:12'>,
 <Frame frame_id='313' time='P1T00:13'>,
 <Frame frame_id='314' time='P1T00:13'>,
 <Frame frame_id='315' time='P1T00:13'>,
 <Frame frame_id='316' time='P1T00:13'>,
 <Frame frame_id='317' time='P1T00:13'>,
 <Frame frame_id='318' time='P1T00:13'>,
 <Frame frame_id='319' time='P1T00:13'>,
 <Frame frame_id='320' time='P1T00:13'>,
 <Frame frame_id='321' time='P1T00:13'>,
 <Frame frame_id='322' time='P1T00:13'>,
 <Frame frame_id='323' time='P1T00:13'>,
 <Frame frame_id='324' time='P1T00:13'>,
 <Frame frame_id='325' time='P1T00:13'>,
 <Frame frame_id='326' time='P1T00:13'>,
 <Frame frame_id='327' time='P1T00:13'>,
 <Frame frame_id='328' time='P1T00:13'>,
 <Frame frame_id='329' time='P1T00:13'>,
 <Frame frame_id='330' time='P1T00:13'>,
 <Frame frame_id='331' time='P1T00:13'>,
 <Frame frame_id='332' time='P1T00:13'>,
 <Frame frame_id='333' time='P1T00:13'>,
 <Frame frame_id='334' time='P1T00:13'>,
 <Frame frame_id='335' time='P1T00:13'>,
 <Frame frame_id='336' time='P1T00:13'>,
 <Frame frame_id='337' time='P1T00:13'>,
 <Frame frame_id='338' time='P1T00:14'>,
 <Frame frame_id='339' time='P1T00:14'>,
 <Frame frame_id='340' time='P1T00:14'>,
 <Frame frame_id='341' time='P1T00:14'>,
 <Frame frame_id='342' time='P1T00:14'>,
 <Frame frame_id='343' time='P1T00:14'>,
 <Frame frame_id='344' time='P1T00:14'>,
 <Frame frame_id='345' time='P1T00:14'>,
 <Frame frame_id='346' time='P1T00:14'>,
 <Frame frame_id='347' time='P1T00:14'>,
 <Frame frame_id='348' time='P1T00:14'>,
 <Frame frame_id='349' time='P1T00:14'>,
 <Frame frame_id='350' time='P1T00:14'>,
 <Frame frame_id='351' time='P1T00:14'>,
 <Frame frame_id='352' time='P1T00:14'>,
 <Frame frame_id='353' time='P1T00:14'>,
 <Frame frame_id='354' time='P1T00:14'>,
 <Frame frame_id='355' time='P1T00:14'>,
 <Frame frame_id='356' time='P1T00:14'>,
 <Frame frame_id='357' time='P1T00:14'>,
 <Frame frame_id='358' time='P1T00:14'>,
 <Frame frame_id='359' time='P1T00:14'>,
 <Frame frame_id='360' time='P1T00:14'>,
 <Frame frame_id='361' time='P1T00:14'>,
 <Frame frame_id='362' time='P1T00:14'>,
 <Frame frame_id='363' time='P1T00:15'>,
 <Frame frame_id='364' time='P1T00:15'>,
 <Frame frame_id='365' time='P1T00:15'>,
 <Frame frame_id='366' time='P1T00:15'>,
 <Frame frame_id='367' time='P1T00:15'>,
 <Frame frame_id='368' time='P1T00:15'>,
 <Frame frame_id='369' time='P1T00:15'>,
 <Frame frame_id='370' time='P1T00:15'>,
 <Frame frame_id='371' time='P1T00:15'>,
 <Frame frame_id='372' time='P1T00:15'>,
 <Frame frame_id='373' time='P1T00:15'>,
 <Frame frame_id='374' time='P1T00:15'>,
 <Frame frame_id='375' time='P1T00:15'>,
 <Frame frame_id='376' time='P1T00:15'>,
 <Frame frame_id='377' time='P1T00:15'>,
 <Frame frame_id='378' time='P1T00:15'>,
 <Frame frame_id='379' time='P1T00:15'>,
 <Frame frame_id='380' time='P1T00:15'>,
 <Frame frame_id='381' time='P1T00:15'>,
 <Frame frame_id='382' time='P1T00:15'>,
 <Frame frame_id='383' time='P1T00:15'>,
 <Frame frame_id='384' time='P1T00:15'>,
 <Frame frame_id='385' time='P1T00:15'>,
 <Frame frame_id='386' time='P1T00:15'>,
 <Frame frame_id='387' time='P1T00:15'>,
 <Frame frame_id='388' time='P1T00:16'>,
 <Frame frame_id='389' time='P1T00:16'>,
 <Frame frame_id='390' time='P1T00:16'>,
 <Frame frame_id='391' time='P1T00:16'>,
 <Frame frame_id='392' time='P1T00:16'>,
 <Frame frame_id='393' time='P1T00:16'>,
 <Frame frame_id='394' time='P1T00:16'>,
 <Frame frame_id='395' time='P1T00:16'>,
 <Frame frame_id='396' time='P1T00:16'>,
 <Frame frame_id='397' time='P1T00:16'>,
 <Frame frame_id='398' time='P1T00:16'>,
 <Frame frame_id='399' time='P1T00:16'>,
 <Frame frame_id='400' time='P1T00:16'>,
 <Frame frame_id='401' time='P1T00:16'>,
 <Frame frame_id='402' time='P1T00:16'>,
 <Frame frame_id='403' time='P1T00:16'>,
 <Frame frame_id='404' time='P1T00:16'>,
 <Frame frame_id='405' time='P1T00:16'>,
 <Frame frame_id='406' time='P1T00:16'>,
 <Frame frame_id='407' time='P1T00:16'>,
 <Frame frame_id='408' time='P1T00:16'>,
 <Frame frame_id='409' time='P1T00:16'>,
 <Frame frame_id='410' time='P1T00:16'>,
 <Frame frame_id='411' time='P1T00:16'>,
 <Frame frame_id='412' time='P1T00:16'>,
 <Frame frame_id='413' time='P1T00:17'>,
 <Frame frame_id='414' time='P1T00:17'>,
 <Frame frame_id='415' time='P1T00:17'>,
 <Frame frame_id='416' time='P1T00:17'>,
 <Frame frame_id='417' time='P1T00:17'>,
 <Frame frame_id='418' time='P1T00:17'>,
 <Frame frame_id='419' time='P1T00:17'>,
 <Frame frame_id='420' time='P1T00:17'>,
 <Frame frame_id='421' time='P1T00:17'>,
 <Frame frame_id='422' time='P1T00:17'>,
 <Frame frame_id='423' time='P1T00:17'>,
 <Frame frame_id='424' time='P1T00:17'>,
 <Frame frame_id='425' time='P1T00:17'>,
 <Frame frame_id='426' time='P1T00:17'>,
 <Frame frame_id='427' time='P1T00:17'>,
 <Frame frame_id='428' time='P1T00:17'>,
 <Frame frame_id='429' time='P1T00:17'>,
 <Frame frame_id='430' time='P1T00:17'>,
 <Frame frame_id='431' time='P1T00:17'>,
 <Frame frame_id='432' time='P1T00:17'>,
 <Frame frame_id='433' time='P1T00:17'>,
 <Frame frame_id='434' time='P1T00:17'>,
 <Frame frame_id='435' time='P1T00:17'>,
 <Frame frame_id='436' time='P1T00:17'>,
 <Frame frame_id='437' time='P1T00:17'>,
 <Frame frame_id='438' time='P1T00:18'>,
 <Frame frame_id='439' time='P1T00:18'>,
 <Frame frame_id='440' time='P1T00:18'>,
 <Frame frame_id='441' time='P1T00:18'>,
 <Frame frame_id='442' time='P1T00:18'>,
 <Frame frame_id='443' time='P1T00:18'>,
 <Frame frame_id='444' time='P1T00:18'>,
 <Frame frame_id='445' time='P1T00:18'>,
 <Frame frame_id='446' time='P1T00:18'>,
 <Frame frame_id='447' time='P1T00:18'>,
 <Frame frame_id='448' time='P1T00:18'>,
 <Frame frame_id='449' time='P1T00:18'>,
 <Frame frame_id='450' time='P1T00:18'>,
 <Frame frame_id='451' time='P1T00:18'>,
 <Frame frame_id='452' time='P1T00:18'>,
 <Frame frame_id='453' time='P1T00:18'>,
 <Frame frame_id='454' time='P1T00:18'>,
 <Frame frame_id='455' time='P1T00:18'>,
 <Frame frame_id='456' time='P1T00:18'>,
 <Frame frame_id='457' time='P1T00:18'>,
 <Frame frame_id='458' time='P1T00:18'>,
 <Frame frame_id='459' time='P1T00:18'>,
 <Frame frame_id='460' time='P1T00:18'>,
 <Frame frame_id='461' time='P1T00:18'>,
 <Frame frame_id='462' time='P1T00:18'>,
 <Frame frame_id='463' time='P1T00:19'>,
 <Frame frame_id='464' time='P1T00:19'>,
 <Frame frame_id='465' time='P1T00:19'>,
 <Frame frame_id='466' time='P1T00:19'>,
 <Frame frame_id='467' time='P1T00:19'>,
 <Frame frame_id='468' time='P1T00:19'>,
 <Frame frame_id='469' time='P1T00:19'>,
 <Frame frame_id='470' time='P1T00:19'>,
 <Frame frame_id='471' time='P1T00:19'>,
 <Frame frame_id='472' time='P1T00:19'>,
 <Frame frame_id='473' time='P1T00:19'>,
 <Frame frame_id='474' time='P1T00:19'>,
 <Frame frame_id='475' time='P1T00:19'>,
 <Frame frame_id='476' time='P1T00:19'>,
 <Frame frame_id='477' time='P1T00:19'>,
 <Frame frame_id='478' time='P1T00:19'>,
 <Frame frame_id='479' time='P1T00:19'>,
 <Frame frame_id='480' time='P1T00:19'>,
 <Frame frame_id='481' time='P1T00:19'>,
 <Frame frame_id='482' time='P1T00:19'>,
 <Frame frame_id='483' time='P1T00:19'>,
 <Frame frame_id='484' time='P1T00:19'>,
 <Frame frame_id='485' time='P1T00:19'>,
 <Frame frame_id='486' time='P1T00:19'>,
 <Frame frame_id='487' time='P1T00:19'>,
 <Frame frame_id='488' time='P1T00:20'>,
 <Frame frame_id='489' time='P1T00:20'>,

In [7]:
df = dataset.to_df()

In [8]:
print(df.shape)
df.columns

(5002, 147)

Index(['period_id', 'timestamp', 'frame_id', 'ball_state',
       'ball_owning_team_id', 'ball_x', 'ball_y', 'ball_z', 'ball_speed',
       '14584_x',
       ...
       '11573_d', '11573_s', '11573_acceleration', '11573_line', '8300_x',
       '8300_y', '8300_d', '8300_s', '8300_acceleration', '8300_line'],
      dtype='object', length=147)

In [9]:
df.head()

,period_id,timestamp,frame_id,ball_state,ball_owning_team_id,ball_x,ball_y,ball_z,ball_speed,14584_x,...,11573_d,11573_s,11573_acceleration,11573_line,8300_x,8300_y,8300_d,8300_s,8300_acceleration,8300_line
0,1,0 days 00:00:00,0,alive,78,0.000048,0.000073,None,7.13,0.000035,...,None,0.00,3.69,midfield,NaN,NaN,None,NaN,NaN,None
1,1,0 days 00:00:00.040000,1,alive,78,0.000047,0.000072,None,7.08,0.000035,...,None,0.64,3.49,midfield,NaN,NaN,None,NaN,NaN,None
2,1,0 days 00:00:00.080000,2,alive,78,0.000046,0.000070,None,7.01,0.000035,...,None,1.29,3.30,midfield,NaN,NaN,None,NaN,NaN,None
3,1,0 days 00:00:00.120000,3,alive,78,0.000045,0.000069,None,6.96,0.000035,...,None,1.35,3.10,midfield,NaN,NaN,None,NaN,NaN,None
4,1,0 days 00:00:00.160000,4,alive,78,0.000045,0.000067,None,6.90,0.000035,...,None,1.41,2.92,midfield,NaN,NaN,None,NaN,NaN,None

In [10]:
df['ball_state'].value_counts()

ball_state
alive    2962
dead     2040
Name: count, dtype: int64

In [9]:
import json

raw_frame = json.load(open("kloppy/tests/files/footovision_tracking.json"))

In [10]:
new_dict = {}

print(raw_frame.keys())

dict_keys(['players', 'ball'])

In [3]:
import json
import pandas as pd
import os

with open("kloppy/tests/files/footovision_tracking.json") as f:
    raw_frame = json.load(f)

new_dict = {}

df_players = (
    pd.DataFrame(raw_frame["players"])
    .sort_values(by=["halftime", "time"])
    .reset_index(drop=True)
)

new_raw_players = []

for halftime in df_players["halftime"].unique():
    df_half = df_players[df_players["halftime"] == halftime].copy()

    start_time = df_half["time"].min()
    small_half = df_half[df_half["time"] <= start_time + 100_000]

    new_raw_players.extend(small_half.to_dict(orient="records"))



df_ball = pd.DataFrame(raw_frame["ball"])

new_raw_ball = []

for halftime in df_ball["halftime"].unique():
    df_half = df_ball[df_ball["halftime"] == halftime].copy()

    start_time = df_half["time"].min()
    small_half = df_half[df_half["time"] <= start_time + 100_000]

    new_raw_ball.extend(small_half.to_dict(orient="records"))


new_dict["players"] = new_raw_players
new_dict["ball"] = new_raw_ball

with open(
    "kloppy/tests/files/footovision_small_tracking.json",
    "w",
) as outfile:
    json.dump(new_dict, outfile)

size_mb = os.path.getsize(
    "kloppy/tests/files/footovision_small_tracking.json"
) / 1024**2

print(f"{size_mb:.2f} MB")

16.52 MB

In [ ]:
with open("kloppy/tests/files/footovision_small_tracking.json", "w") as outfile:
    json.dump(new_dict, outfile)

In [5]:
raw_frame["players"]

[{'playerId': 19815,
  'teamId': 414,
  'halftime': 1,
  'time': 1186680,
  'x': 0.323,
  'y': 0.367,
  'speed': 5.71,
  'accel': -0.15,
  'line': 'defence',
  'isObs': True},
 {'playerId': 20182,
  'teamId': 414,
  'halftime': 1,
  'time': 1186680,
  'x': 0.442,
  'y': 0.595,
  'speed': 3.96,
  'accel': -0.2,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 21662,
  'teamId': 414,
  'halftime': 1,
  'time': 1186680,
  'x': 0.366,
  'y': 0.851,
  'speed': 1.28,
  'accel': -0.04,
  'line': 'defence',
  'isObs': True},
 {'playerId': 21778,
  'teamId': 414,
  'halftime': 1,
  'time': 1186680,
  'x': 0.538,
  'y': 0.189,
  'speed': 2.34,
  'accel': -0.55,
  'line': 'attack',
  'isObs': True},
 {'playerId': 23676,
  'teamId': 414,
  'halftime': 1,
  'time': 1186680,
  'x': 0.536,
  'y': 0.95,
  'speed': 1.05,
  'accel': -0.28,
  'line': 'attack',
  'isObs': True},
 {'playerId': 1999,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.574,
  'y': 0.632,
  'speed': 3.11,
  'accel': -0.02,
  'line': 'defence',
  'isObs': True},
 {'playerId': 6660,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.3,
  'y': 0.162,
  'speed': 2.36,
  'accel': -5.51,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8102,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.437,
  'y': 0.269,
  'speed': 3.58,
  'accel': -1.1,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 8225,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.566,
  'y': 0.177,
  'speed': 2.5,
  'accel': 1.14,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8300,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.336,
  'y': 0.442,
  'speed': 7.06,
  'accel': 0.58,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8681,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.828,
  'y': 0.47,
  'speed': 0.9,
  'accel': -0.34,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 8808,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.419,
  'y': 0.484,
  'speed': 2.39,
  'accel': -1.56,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 8831,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.505,
  'y': 0.545,
  'speed': 2.66,
  'accel': 0.37,
  'line': 'defence',
  'isObs': True},
 {'playerId': 11284,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.584,
  'y': 0.436,
  'speed': 2.83,
  'accel': -0.72,
  'line': 'defence',
  'isObs': True},
 {'playerId': 11573,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.248,
  'y': 0.391,
  'speed': 2.56,
  'accel': -0.48,
  'line': 'attack',
  'isObs': True},
 {'playerId': 20601,
  'teamId': 78,
  'halftime': 1,
  'time': 1186680,
  'x': 0.556,
  'y': 0.779,
  'speed': 1.33,
  'accel': -0.07,
  'line': 'defence',
  'isObs': True},
 {'playerId': 628,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.554,
  'y': 0.563,
  'speed': 1.54,
  'accel': 0.11,
  'line': 'attack',
  'isObs': True},
 {'playerId': 687,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.326,
  'y': 0.638,
  'speed': 3.6,
  'accel': -0.7,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8569,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.271,
  'y': 0.154,
  'speed': 3.28,
  'accel': 2.07,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8572,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.492,
  'y': 0.727,
  'speed': 3.29,
  'accel': -0.36,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 10668,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.204,
  'y': 0.426,
  'speed': 3.13,
  'accel': 0.34,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 14584,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.455,
  'y': 0.302,
  'speed': 2.77,
  'accel': -1.31,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 19815,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.323,
  'y': 0.364,
  'speed': 5.72,
  'accel': -0.11,
  'line': 'defence',
  'isObs': True},
 {'playerId': 20182,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.441,
  'y': 0.593,
  'speed': 3.97,
  'accel': -0.21,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 21662,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.366,
  'y': 0.85,
  'speed': 1.28,
  'accel': -0.01,
  'line': 'defence',
  'isObs': True},
 {'playerId': 21778,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.537,
  'y': 0.189,
  'speed': 2.34,
  'accel': -0.58,
  'line': 'attack',
  'isObs': True},
 {'playerId': 23676,
  'teamId': 414,
  'halftime': 1,
  'time': 1186720,
  'x': 0.535,
  'y': 0.949,
  'speed': 1.04,
  'accel': -0.33,
  'line': 'attack',
  'isObs': True},
 {'playerId': 1999,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.574,
  'y': 0.63,
  'speed': 3.09,
  'accel': -0.04,
  'line': 'defence',
  'isObs': True},
 {'playerId': 6660,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.299,
  'y': 0.161,
  'speed': 2.12,
  'accel': -5.27,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8102,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.437,
  'y': 0.267,
  'speed': 3.53,
  'accel': -1.16,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 8225,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.565,
  'y': 0.177,
  'speed': 2.57,
  'accel': 0.98,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8300,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.336,
  'y': 0.438,
  'speed': 7.05,
  'accel': 0.58,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8681,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.828,
  'y': 0.47,
  'speed': 0.9,
  'accel': -0.35,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 8808,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.418,
  'y': 0.484,
  'speed': 2.33,
  'accel': -1.53,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 8831,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.504,
  'y': 0.544,
  'speed': 2.62,
  'accel': 0.33,
  'line': 'defence',
  'isObs': True},
 {'playerId': 11284,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.584,
  'y': 0.434,
  'speed': 2.8,
  'accel': -0.78,
  'line': 'defence',
  'isObs': True},
 {'playerId': 11573,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.249,
  'y': 0.39,
  'speed': 2.6,
  'accel': -0.33,
  'line': 'attack',
  'isObs': True},
 {'playerId': 20601,
  'teamId': 78,
  'halftime': 1,
  'time': 1186720,
  'x': 0.555,
  'y': 0.779,
  'speed': 1.29,
  'accel': -0.09,
  'line': 'defence',
  'isObs': True},
 {'playerId': 628,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.554,
  'y': 0.562,
  'speed': 1.57,
  'accel': 0.12,
  'line': 'attack',
  'isObs': True},
 {'playerId': 687,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.325,
  'y': 0.638,
  'speed': 3.58,
  'accel': -0.69,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8569,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.27,
  'y': 0.155,
  'speed': 3.35,
  'accel': 1.87,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8572,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.491,
  'y': 0.725,
  'speed': 3.28,
  'accel': -0.37,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 10668,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.203,
  'y': 0.425,
  'speed': 3.2,
  'accel': 0.21,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 14584,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.454,
  'y': 0.301,
  'speed': 2.75,
  'accel': -1.41,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 19815,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.323,
  'y': 0.361,
  'speed': 5.71,
  'accel': -0.09,
  'line': 'defence',
  'isObs': True},
 {'playerId': 20182,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.44,
  'y': 0.591,
  'speed': 3.96,
  'accel': -0.21,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 21662,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.365,
  'y': 0.849,
  'speed': 1.28,
  'accel': 0.03,
  'line': 'defence',
  'isObs': True},
 {'playerId': 21778,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.536,
  'y': 0.188,
  'speed': 2.35,
  'accel': -0.63,
  'line': 'attack',
  'isObs': True},
 {'playerId': 23676,
  'teamId': 414,
  'halftime': 1,
  'time': 1186760,
  'x': 0.535,
  'y': 0.949,
  'speed': 1.06,
  'accel': -0.38,
  'line': 'attack',
  'isObs': True},
 {'playerId': 1999,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.574,
  'y': 0.628,
  'speed': 3.09,
  'accel': -0.05,
  'line': 'defence',
  'isObs': True},
 {'playerId': 6660,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.299,
  'y': 0.16,
  'speed': 1.87,
  'accel': -4.97,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8102,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.436,
  'y': 0.265,
  'speed': 3.5,
  'accel': -1.24,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 8225,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.564,
  'y': 0.178,
  'speed': 2.58,
  'accel': 0.81,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8300,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.336,
  'y': 0.434,
  'speed': 7.1,
  'accel': 0.57,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8681,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.827,
  'y': 0.469,
  'speed': 0.9,
  'accel': -0.35,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 8808,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.417,
  'y': 0.483,
  'speed': 2.27,
  'accel': -1.46,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 8831,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.503,
  'y': 0.543,
  'speed': 2.6,
  'accel': 0.29,
  'line': 'defence',
  'isObs': True},
 {'playerId': 11284,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.584,
  'y': 0.433,
  'speed': 2.75,
  'accel': -0.83,
  'line': 'defence',
  'isObs': True},
 {'playerId': 11573,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.249,
  'y': 0.389,
  'speed': 2.59,
  'accel': -0.18,
  'line': 'attack',
  'isObs': True},
 {'playerId': 20601,
  'teamId': 78,
  'halftime': 1,
  'time': 1186760,
  'x': 0.555,
  'y': 0.779,
  'speed': 1.27,
  'accel': -0.12,
  'line': 'defence',
  'isObs': True},
 {'playerId': 628,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.554,
  'y': 0.561,
  'speed': 1.61,
  'accel': 0.14,
  'line': 'attack',
  'isObs': True},
 {'playerId': 687,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.324,
  'y': 0.638,
  'speed': 3.53,
  'accel': -0.68,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8569,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.27,
  'y': 0.157,
  'speed': 3.42,
  'accel': 1.64,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8572,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.49,
  'y': 0.724,
  'speed': 3.26,
  'accel': -0.37,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 10668,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.202,
  'y': 0.426,
  'speed': 3.25,
  'accel': 0.08,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 14584,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.453,
  'y': 0.3,
  'speed': 2.7,
  'accel': -1.52,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 19815,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.323,
  'y': 0.357,
  'speed': 5.75,
  'accel': -0.1,
  'line': 'defence',
  'isObs': True},
 {'playerId': 20182,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.439,
  'y': 0.589,
  'speed': 3.98,
  'accel': -0.23,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 21662,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.365,
  'y': 0.848,
  'speed': 1.32,
  'accel': 0.06,
  'line': 'defence',
  'isObs': True},
 {'playerId': 21778,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.535,
  'y': 0.188,
  'speed': 2.34,
  'accel': -0.68,
  'line': 'attack',
  'isObs': True},
 {'playerId': 23676,
  'teamId': 414,
  'halftime': 1,
  'time': 1186800,
  'x': 0.535,
  'y': 0.948,
  'speed': 1.04,
  'accel': -0.45,
  'line': 'attack',
  'isObs': True},
 {'playerId': 1999,
  'teamId': 78,
  'halftime': 1,
  'time': 1186800,
  'x': 0.574,
  'y': 0.626,
  'speed': 3.12,
  'accel': -0.05,
  'line': 'defence',
  'isObs': True},
 {'playerId': 6660,
  'teamId': 78,
  'halftime': 1,
  'time': 1186800,
  'x': 0.298,
  'y': 0.16,
  'speed': 1.66,
  'accel': -4.64,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8102,
  'teamId': 78,
  'halftime': 1,
  'time': 1186800,
  'x': 0.436,
  'y': 0.263,
  'speed': 3.44,
  'accel': -1.32,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 8225,
  'teamId': 78,
  'halftime': 1,
  'time': 1186800,
  'x': 0.563,
  'y': 0.178,
  'speed': 2.59,
  'accel': 0.65,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8102,
  'teamId': 78,
  'halftime': 1,
  'time': 1325240,
  'x': 0.14,
  'y': 0.128,
  'speed': 3.25,
  'accel': -0.11,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 8225,
  'teamId': 78,
  'halftime': 1,
  'time': 1325240,
  'x': 0.307,
  'y': 0.479,
  'speed': 0.59,
  'accel': -0.55,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8300,
  'teamId': 78,
  'halftime': 1,
  'time': 1325240,
  'x': 0.09,
  'y': 0.531,
  'speed': 1,
  'accel': -0.42,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8681,
  'teamId': 78,
  'halftime': 1,
  'time': 1325240,
  'x': 0.649,
  'y': 0.503,
  'speed': 1,
  'accel': 0.19,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 8808,
  'teamId': 78,
  'halftime': 1,
  'time': 1325240,
  'x': 0.099,
  'y': 0.593,
  'speed': 2.89,
  'accel': 1.32,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8831,
  'teamId': 78,
  'halftime': 1,
  'time': 1325240,
  'x': 0.147,
  'y': 0.431,
  'speed': 1.08,
  'accel': 0.6,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 11284,
  'teamId': 78,
  'halftime': 1,
  'time': 1325240,
  'x': 0.114,
  'y': 0.514,
  'speed': 1.31,
  'accel': -0.22,
  'line': 'attack',
  'isObs': True},
 {'playerId': 11573,
  'teamId': 78,
  'halftime': 1,
  'time': 1325240,
  'x': 0.216,
  'y': 0.638,
  'speed': 1.54,
  'accel': 1.52,
  'line': 'defence',
  'isObs': True},
 {'playerId': 20601,
  'teamId': 78,
  'halftime': 1,
  'time': 1325240,
  'x': 0.219,
  'y': 0.515,
  'speed': 0.41,
  'accel': 0.43,
  'line': 'defence',
  'isObs': True},
 {'playerId': 628,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.09,
  'y': 0.552,
  'speed': 0.74,
  'accel': -0.03,
  'line': 'defence',
  'isObs': True},
 {'playerId': 687,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.071,
  'y': 0.569,
  'speed': 1.54,
  'accel': 1.3,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8569,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.082,
  'y': 0.569,
  'speed': 0.59,
  'accel': -0.66,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8572,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.174,
  'y': 0.673,
  'speed': 2.01,
  'accel': 1.56,
  'line': 'attack',
  'isObs': True},
 {'playerId': 10668,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.018,
  'y': 0.511,
  'speed': 0.16,
  'accel': 0.89,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 14584,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.163,
  'y': 0.537,
  'speed': 1.01,
  'accel': 2.37,
  'line': 'attack',
  'isObs': True},
 {'playerId': 19815,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.09,
  'y': 0.496,
  'speed': 0.84,
  'accel': 1.27,
  'line': 'defence',
  'isObs': True},
 {'playerId': 20182,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.078,
  'y': 0.52,
  'speed': 0.46,
  'accel': -0.7,
  'line': 'defence',
  'isObs': True},
 {'playerId': 21662,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.106,
  'y': 0.643,
  'speed': 1.93,
  'accel': 1.8,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 21778,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.117,
  'y': 0.43,
  'speed': 0.65,
  'accel': -0.7,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 23676,
  'teamId': 414,
  'halftime': 1,
  'time': 1325280,
  'x': 0.086,
  'y': 0.483,
  'speed': 0.24,
  'accel': -0.25,
  'line': 'defence',
  'isObs': True},
 {'playerId': 1999,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.183,
  'y': 0.709,
  'speed': 0.05,
  'accel': -0.48,
  'line': 'defence',
  'isObs': True},
 {'playerId': 6660,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.081,
  'y': 0.496,
  'speed': 0.13,
  'accel': 0.56,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8102,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.141,
  'y': 0.129,
  'speed': 3.28,
  'accel': -0.11,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 8225,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.307,
  'y': 0.479,
  'speed': 0.56,
  'accel': -0.58,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8300,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.09,
  'y': 0.531,
  'speed': 0.96,
  'accel': -0.33,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8681,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.65,
  'y': 0.503,
  'speed': 1,
  'accel': 0.15,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 8808,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.1,
  'y': 0.592,
  'speed': 2.97,
  'accel': 1.16,
  'line': 'attack',
  'isObs': True},
 {'playerId': 8831,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.147,
  'y': 0.432,
  'speed': 1.1,
  'accel': 0.49,
  'line': 'midfield',
  'isObs': True},
 {'playerId': 11284,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.114,
  'y': 0.515,
  'speed': 1.33,
  'accel': -0.13,
  'line': 'attack',
  'isObs': True},
 {'playerId': 11573,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.216,
  'y': 0.637,
  'speed': 1.6,
  'accel': 1.44,
  'line': 'defence',
  'isObs': True},
 {'playerId': 20601,
  'teamId': 78,
  'halftime': 1,
  'time': 1325280,
  'x': 0.218,
  'y': 0.515,
  'speed': 0.54,
  'accel': 0.79,
  'line': 'defence',
  'isObs': True},
 {'playerId': 628,
  'teamId': 414,
  'halftime': 1,
  'time': 1325320,
  'x': 0.089,
  'y': 0.551,
  'speed': 0.72,
  'accel': -0.14,
  'line': 'defence',
  'isObs': True},
 {'playerId': 687,
  'teamId': 414,
  'halftime': 1,
  'time': 1325320,
  'x': 0.071,
  'y': 0.569,
  'speed': 1.61,
  'accel': 1.31,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8569,
  'teamId': 414,
  'halftime': 1,
  'time': 1325320,
  'x': 0.081,
  'y': 0.569,
  'speed': 0.58,
  'accel': -0.48,
  'line': 'defence',
  'isObs': True},
 {'playerId': 8572,
  'teamId': 414,
  'halftime': 1,
  'time': 1325320,
  'x': 0.173,
  'y': 0.672,
  'speed': 2.08,
  'accel': 1.55,
  'line': 'attack',
  'isObs': True},
 {'playerId': 10668,
  'teamId': 414,
  'halftime': 1,
  'time': 1325320,
  'x': 0.018,
  'y': 0.511,
  'speed': 0.22,
  'accel': 0.89,
  'line': 'goalkeeper',
  'isObs': True},
 {'playerId': 14584,
  'teamId': 414,
  'halftime': 1,
  'time': 1325320,
  'x': 0.162,
  'y': 0.537,
  'speed': 1.14,
  'accel': 2.61,
  'line': 'attack',
  'isObs': True},
 {'playerId': 19815,
  'teamId': 414,
  'halftime': 1,
  'time': 1325320,
  'x': 0.09,
  'y': 0.496,
  'speed': 0.89,
  'accel': 1.25,
  'line': 'defence',
  'isObs': True},
 {'playerId': 20182,
  'teamId': 414,
  'halftime': 1,
  'time': 1325320,
  'x': 0.078,
  'y': 0.521,
  'speed': 0.44,
  'accel': -0.66,
  'line': 'defence',
  'isObs': True},
 {'playerId': 21662,
  'teamId': 414,
  'halftime': 1,
  'time': 1325320,
  'x': 0.106,
  'y': 0.642,
  'speed': 2,
  'accel': 1.67,

In [6]:
import pandas as pd

df = pd.DataFrame(raw_frame["players"])

In [7]:
df.head()

,playerId,teamId,halftime,time,x,y,speed,accel,line,isObs
0,19815,414,1,1186680,0.323,0.367,5.71,-0.15,defence,True
1,20182,414,1,1186680,0.442,0.595,3.96,-0.20,midfield,True
2,21662,414,1,1186680,0.366,0.851,1.28,-0.04,defence,True
3,21778,414,1,1186680,0.538,0.189,2.34,-0.55,attack,True
4,23676,414,1,1186680,0.536,0.950,1.05,-0.28,attack,True